/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.utfpr.projetoanalisedesistemas;

import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author ferna
 */
public class CardScreen extends Screen {

    /**
     * Creates new form CardScreen
     */
    public CardScreen() {
        super("cardScreen");
        initComponents();
        try {
            f_data.setFormatterFactory(new DefaultFormatterFactory(new MaskFormatter("##/##")));
            f_cardNumber.setFormatterFactory(new DefaultFormatterFactory(new MaskFormatter("#### #### #### ####")));
        } catch (ParseException ex) {
            Logger.getLogger(CardScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardScreen = new javax.swing.JPanel();
        btn_finCompra = new javax.swing.JButton();
        p_name = new javax.swing.JPanel();
        f_person = new javax.swing.JTextField();
        l_name = new javax.swing.JLabel();
        p_cvv = new javax.swing.JPanel();
        l_cvv = new javax.swing.JLabel();
        f_cvv = new javax.swing.JPasswordField();
        p_number = new javax.swing.JPanel();
        l_number = new javax.swing.JLabel();
        f_cardNumber = new javax.swing.JFormattedTextField();
        p_validade = new javax.swing.JPanel();
        l_validade = new javax.swing.JLabel();
        f_data = new javax.swing.JFormattedTextField();
        p_title = new javax.swing.JPanel();
        l_title = new javax.swing.JLabel();
        btn_cancelar = new javax.swing.JButton();

        setBackground(new java.awt.Color(247, 245, 245));
        setPreferredSize(new java.awt.Dimension(1280, 800));

        cardScreen.setBackground(new java.awt.Color(247, 245, 245));
        cardScreen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0), 25));
        cardScreen.setPreferredSize(new java.awt.Dimension(1280, 800));

        btn_finCompra.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn_finCompra.setText("FINALIZAR COMPRA");
        btn_finCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_finCompraActionPerformed(evt);
            }
        });

        p_name.setBackground(new java.awt.Color(247, 245, 245));
        p_name.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 0), 4, true));
        p_name.setPreferredSize(new java.awt.Dimension(870, 58));

        f_person.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        f_person.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        l_name.setBackground(new java.awt.Color(247, 245, 245));
        l_name.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        l_name.setText("NOME DO TITULAR");
        l_name.setOpaque(true);

        javax.swing.GroupLayout p_nameLayout = new javax.swing.GroupLayout(p_name);
        p_name.setLayout(p_nameLayout);
        p_nameLayout.setHorizontalGroup(
            p_nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_nameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l_name, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addComponent(f_person, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );
        p_nameLayout.setVerticalGroup(
            p_nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(l_name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(f_person, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        p_cvv.setBackground(new java.awt.Color(247, 245, 245));
        p_cvv.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 0), 4, true));
        p_cvv.setPreferredSize(new java.awt.Dimension(190, 58));

        l_cvv.setBackground(new java.awt.Color(247, 245, 245));
        l_cvv.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        l_cvv.setText("CVV");

        f_cvv.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        f_cvv.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout p_cvvLayout = new javax.swing.GroupLayout(p_cvv);
        p_cvv.setLayout(p_cvvLayout);
        p_cvvLayout.setHorizontalGroup(
            p_cvvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_cvvLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(l_cvv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(f_cvv, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        p_cvvLayout.setVerticalGroup(
            p_cvvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(l_cvv, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(f_cvv)
        );

        p_number.setBackground(new java.awt.Color(247, 245, 245));
        p_number.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 0), 4, true));
        p_number.setPreferredSize(new java.awt.Dimension(870, 58));

        l_number.setBackground(new java.awt.Color(247, 245, 245));
        l_number.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        l_number.setLabelFor(f_cardNumber);
        l_number.setText("NUMERO DO CARTAO");
        l_number.setOpaque(true);

        f_cardNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        f_cardNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        f_cardNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_cardNumberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_numberLayout = new javax.swing.GroupLayout(p_number);
        p_number.setLayout(p_numberLayout);
        p_numberLayout.setHorizontalGroup(
            p_numberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_numberLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l_number, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addComponent(f_cardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        p_numberLayout.setVerticalGroup(
            p_numberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(l_number, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(f_cardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        p_validade.setBackground(new java.awt.Color(247, 245, 245));
        p_validade.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 0), 4, true));
        p_validade.setPreferredSize(new java.awt.Dimension(229, 58));

        l_validade.setBackground(new java.awt.Color(247, 245, 245));
        l_validade.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        l_validade.setText("VALIDADE");
        l_validade.setOpaque(true);

        f_data.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        f_data.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout p_validadeLayout = new javax.swing.GroupLayout(p_validade);
        p_validade.setLayout(p_validadeLayout);
        p_validadeLayout.setHorizontalGroup(
            p_validadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_validadeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l_validade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(f_data, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                .addContainerGap())
        );
        p_validadeLayout.setVerticalGroup(
            p_validadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(l_validade, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(f_data)
        );

        p_title.setBackground(new java.awt.Color(247, 245, 245));
        p_title.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 0), 4, true));

        l_title.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        l_title.setText("PREENCHA AS INFORMAÇÕES");

        javax.swing.GroupLayout p_titleLayout = new javax.swing.GroupLayout(p_title);
        p_title.setLayout(p_titleLayout);
        p_titleLayout.setHorizontalGroup(
            p_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_titleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l_title)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p_titleLayout.setVerticalGroup(
            p_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_titleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l_title)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_cancelar.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        btn_cancelar.setText("CANCELAR");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cardScreenLayout = new javax.swing.GroupLayout(cardScreen);
        cardScreen.setLayout(cardScreenLayout);
        cardScreenLayout.setHorizontalGroup(
            cardScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardScreenLayout.createSequentialGroup()
                .addContainerGap(188, Short.MAX_VALUE)
                .addGroup(cardScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardScreenLayout.createSequentialGroup()
                        .addGroup(cardScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(cardScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(cardScreenLayout.createSequentialGroup()
                                    .addGap(216, 216, 216)
                                    .addComponent(p_title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(p_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(cardScreenLayout.createSequentialGroup()
                                .addComponent(p_cvv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(p_validade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(160, 160, 160))
                            .addComponent(p_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(172, 172, 172))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardScreenLayout.createSequentialGroup()
                        .addGroup(cardScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btn_finCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(458, 458, 458))))
        );
        cardScreenLayout.setVerticalGroup(
            cardScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardScreenLayout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addComponent(p_title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(p_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(p_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(cardScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(p_validade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p_cvv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(btn_finCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(cardScreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(cardScreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_finCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_finCompraActionPerformed
        JOptionPane.showMessageDialog(null,"Compra Confirmada, Verifique Seu Email", "Confirmação",1);
        Screen loginScreen = new LoginScreen();
        MainClass.switchScreen(loginScreen, loginScreen.getName());
    }//GEN-LAST:event_btn_finCompraActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        Screen purchaseScreen = new PurchaseScreen();
        MainClass.switchScreen(purchaseScreen, purchaseScreen.getName());
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void f_cardNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_cardNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f_cardNumberActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_finCompra;
    private javax.swing.JPanel cardScreen;
    private javax.swing.JFormattedTextField f_cardNumber;
    private javax.swing.JPasswordField f_cvv;
    private javax.swing.JFormattedTextField f_data;
    private javax.swing.JTextField f_person;
    private javax.swing.JLabel l_cvv;
    private javax.swing.JLabel l_name;
    private javax.swing.JLabel l_number;
    private javax.swing.JLabel l_title;
    private javax.swing.JLabel l_validade;
    private javax.swing.JPanel p_cvv;
    private javax.swing.JPanel p_name;
    private javax.swing.JPanel p_number;
    private javax.swing.JPanel p_title;
    private javax.swing.JPanel p_validade;
    // End of variables declaration//GEN-END:variables
}
