/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.utfpr.projetoanalisedesistemas;

import javax.swing.JOptionPane;

/**
 *
 * @author ferna
 */
public class LoginScreen extends Screen {

    /**
     * Creates new form LoginScreen
     */
    public LoginScreen() {
        super("loginScreen");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginScreen = new javax.swing.JPanel();
        p_firstLog = new javax.swing.JPanel();
        p_home = new javax.swing.JPanel();
        l_Home = new javax.swing.JLabel();
        p_ra = new javax.swing.JPanel();
        p_auxRA = new javax.swing.JPanel();
        f_ra = new javax.swing.JTextField();
        l_ra = new javax.swing.JLabel();
        p_password = new javax.swing.JPanel();
        p_auxPassword = new javax.swing.JPanel();
        f_password = new javax.swing.JPasswordField();
        l_password = new javax.swing.JLabel();
        p_bntlogin = new javax.swing.JPanel();
        btn_login = new javax.swing.JToggleButton();
        p_aviso = new javax.swing.JPanel();
        l_aviso = new javax.swing.JLabel();
        panelLogo = new javax.swing.JPanel();
        l_logo = new javax.swing.JLabel();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1280, 800));

        loginScreen.setBackground(new java.awt.Color(255, 204, 0));
        loginScreen.setPreferredSize(new java.awt.Dimension(1280, 800));

        p_firstLog.setOpaque(false);
        p_firstLog.setPreferredSize(new java.awt.Dimension(615, 794));

        p_home.setBackground(new java.awt.Color(247, 245, 245));
        p_home.setPreferredSize(new java.awt.Dimension(400, 90));

        l_Home.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        l_Home.setText("SELF-RU - Faça seu Login!");

        javax.swing.GroupLayout p_homeLayout = new javax.swing.GroupLayout(p_home);
        p_home.setLayout(p_homeLayout);
        p_homeLayout.setHorizontalGroup(
            p_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_homeLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(l_Home)
                .addContainerGap(94, Short.MAX_VALUE))
        );
        p_homeLayout.setVerticalGroup(
            p_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_homeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(l_Home, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        p_ra.setBackground(new java.awt.Color(247, 245, 245));
        p_ra.setPreferredSize(new java.awt.Dimension(400, 100));
        p_ra.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        p_auxRA.setBackground(new java.awt.Color(247, 245, 245));
        p_auxRA.setPreferredSize(new java.awt.Dimension(360, 55));
        p_auxRA.setLayout(new java.awt.BorderLayout(4, 4));

        f_ra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_raActionPerformed(evt);
            }
        });
        p_auxRA.add(f_ra, java.awt.BorderLayout.CENTER);

        l_ra.setBackground(new java.awt.Color(247, 245, 245));
        l_ra.setText("Registro de Aluno");
        p_auxRA.add(l_ra, java.awt.BorderLayout.PAGE_START);

        p_ra.add(p_auxRA);

        p_password.setBackground(new java.awt.Color(247, 245, 245));
        p_password.setPreferredSize(new java.awt.Dimension(400, 80));
        p_password.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        p_auxPassword.setBackground(new java.awt.Color(247, 245, 245));
        p_auxPassword.setPreferredSize(new java.awt.Dimension(360, 55));
        p_auxPassword.setLayout(new java.awt.BorderLayout(4, 4));

        f_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_passwordActionPerformed(evt);
            }
        });
        p_auxPassword.add(f_password, java.awt.BorderLayout.CENTER);

        l_password.setBackground(new java.awt.Color(255, 255, 255));
        l_password.setText("Senha");
        p_auxPassword.add(l_password, java.awt.BorderLayout.PAGE_START);

        p_password.add(p_auxPassword);

        p_bntlogin.setBackground(new java.awt.Color(247, 245, 245));
        p_bntlogin.setOpaque(false);
        p_bntlogin.setPreferredSize(new java.awt.Dimension(400, 80));

        btn_login.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_login.setText("Entrar");
        btn_login.setBorder(null);
        btn_login.setBorderPainted(false);
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_bntloginLayout = new javax.swing.GroupLayout(p_bntlogin);
        p_bntlogin.setLayout(p_bntloginLayout);
        p_bntloginLayout.setHorizontalGroup(
            p_bntloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_login, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        p_bntloginLayout.setVerticalGroup(
            p_bntloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_bntloginLayout.createSequentialGroup()
                .addGap(0, 30, Short.MAX_VALUE)
                .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        p_aviso.setBackground(new java.awt.Color(247, 245, 245));
        p_aviso.setPreferredSize(new java.awt.Dimension(603, 20));

        l_aviso.setFont(new java.awt.Font("Segoe UI", 2, 8)); // NOI18N
        l_aviso.setText("* A senha é a mesma do Portal do Aluno");

        javax.swing.GroupLayout p_avisoLayout = new javax.swing.GroupLayout(p_aviso);
        p_aviso.setLayout(p_avisoLayout);
        p_avisoLayout.setHorizontalGroup(
            p_avisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_avisoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(l_aviso)
                .addGap(230, 230, 230))
        );
        p_avisoLayout.setVerticalGroup(
            p_avisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_avisoLayout.createSequentialGroup()
                .addComponent(l_aviso, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout p_firstLogLayout = new javax.swing.GroupLayout(p_firstLog);
        p_firstLog.setLayout(p_firstLogLayout);
        p_firstLogLayout.setHorizontalGroup(
            p_firstLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_firstLogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_firstLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p_home, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)
                    .addComponent(p_ra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p_password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p_bntlogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)
                    .addComponent(p_aviso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        p_firstLogLayout.setVerticalGroup(
            p_firstLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_firstLogLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(p_home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126)
                .addComponent(p_ra, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(p_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(p_bntlogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 198, Short.MAX_VALUE)
                .addComponent(p_aviso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelLogo.setBackground(new java.awt.Color(247, 245, 245));
        panelLogo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0), 4));
        panelLogo.setPreferredSize(new java.awt.Dimension(640, 800));

        l_logo.setBackground(new java.awt.Color(247, 245, 245));
        l_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/selfru.png"))); // NOI18N
        l_logo.setOpaque(true);

        javax.swing.GroupLayout panelLogoLayout = new javax.swing.GroupLayout(panelLogo);
        panelLogo.setLayout(panelLogoLayout);
        panelLogoLayout.setHorizontalGroup(
            panelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogoLayout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(l_logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(134, 134, 134))
        );
        panelLogoLayout.setVerticalGroup(
            panelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogoLayout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(l_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout loginScreenLayout = new javax.swing.GroupLayout(loginScreen);
        loginScreen.setLayout(loginScreenLayout);
        loginScreenLayout.setHorizontalGroup(
            loginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p_firstLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(panelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        loginScreenLayout.setVerticalGroup(
            loginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginScreenLayout.createSequentialGroup()
                .addGroup(loginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginScreenLayout.createSequentialGroup()
                        .addComponent(p_firstLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(loginScreenLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(loginScreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(loginScreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void f_raActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_raActionPerformed
        verificaLogin();
            
    }//GEN-LAST:event_f_raActionPerformed

    private void verificaLogin(){
        if(MainClass.bancoDeDados.verificaDadosAluno(f_ra.getText(), f_password.getText())){
            MainClass.bancoDeDados.imprimeInfoAlunoValidado();
            Aluno est = MainClass.bancoDeDados.retornaEstudanteValidado();
            if(MainClass.alunoComprou(est)){
                JOptionPane.showMessageDialog(this, "Aluno já comprou!", "Alerta", 0);
            }
            else{
                Screen.setEstudanteLogado(est);
                //MainClass.addAluno(Screen.getEstudanteLogado());

                Screen optionScreen = new OptionScreen();
                MainClass.switchScreen(optionScreen, optionScreen.getName());
            }
        }else
           JOptionPane.showMessageDialog(this, "Dados Invalidos!", "Alerta", 0);
    }
    
    private void f_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_passwordActionPerformed
        verificaLogin();
    }//GEN-LAST:event_f_passwordActionPerformed

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        verificaLogin();
    }//GEN-LAST:event_btn_loginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn_login;
    private javax.swing.JPasswordField f_password;
    private javax.swing.JTextField f_ra;
    private javax.swing.JLabel l_Home;
    private javax.swing.JLabel l_aviso;
    private javax.swing.JLabel l_logo;
    private javax.swing.JLabel l_password;
    private javax.swing.JLabel l_ra;
    private javax.swing.JPanel loginScreen;
    private javax.swing.JPanel p_auxPassword;
    private javax.swing.JPanel p_auxRA;
    private javax.swing.JPanel p_aviso;
    private javax.swing.JPanel p_bntlogin;
    private javax.swing.JPanel p_firstLog;
    private javax.swing.JPanel p_home;
    private javax.swing.JPanel p_password;
    private javax.swing.JPanel p_ra;
    private javax.swing.JPanel panelLogo;
    // End of variables declaration//GEN-END:variables
}
