/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.utfpr.projetoanalisedesistemas;

import java.awt.CardLayout;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.security.auth.login.LoginContext;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


public class MainClass extends javax.swing.JFrame {

    /**
     * Creates new form MainClass
     */
    protected static BancoDeDados bancoDeDados;
    
    public MainClass() {
        bancoDeDados = new BancoDeDados();
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 51));
        setResizable(false);

        panelPai.setBackground(new java.awt.Color(255, 204, 51));
        panelPai.setPreferredSize(new java.awt.Dimension(1280, 800));
        panelPai.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPai, javax.swing.GroupLayout.DEFAULT_SIZE, 822, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * @param args the command line arguments
     */ 
    static void switchScreen(Screen screen, String cardName){
            panelPai.add(screen, cardName);
            CardLayout cl = (CardLayout) panelPai.getLayout();
            cl.show(panelPai, cardName);
    }
    
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame window = new MainClass();
                window.setVisible(true);
                Screen loginScreen = new LoginScreen();
                switchScreen(loginScreen, "loginScreen");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static final javax.swing.JPanel panelPai = new javax.swing.JPanel();
    // End of variables declaration//GEN-END:variables
}