/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.utfpr.projetoanalisedesistemas;

import java.awt.CardLayout;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ferna
 */
public class ProjetoAnaliseDeSistemas extends javax.swing.JFrame {

    /**
     * Creates new form ProjetoAnaliseDeSistemas
     */
    
    private final BancoDeDados bancoDeDados;
    
    public ProjetoAnaliseDeSistemas() {
        bancoDeDados = new BancoDeDados();
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPai = new javax.swing.JPanel();
        loginScreen = new javax.swing.JPanel();
        panelLogin = new javax.swing.JPanel();
        p_firstLog = new javax.swing.JPanel();
        p_home = new javax.swing.JPanel();
        l_Home = new javax.swing.JLabel();
        p_ra = new javax.swing.JPanel();
        p_auxRA = new javax.swing.JPanel();
        f_ra = new javax.swing.JTextField();
        l_ra = new javax.swing.JLabel();
        p_password = new javax.swing.JPanel();
        p_auxPassword = new javax.swing.JPanel();
        f_password = new javax.swing.JPasswordField();
        l_password = new javax.swing.JLabel();
        p_bntlogin = new javax.swing.JPanel();
        btn_login = new javax.swing.JToggleButton();
        p_aviso = new javax.swing.JPanel();
        l_aviso = new javax.swing.JLabel();
        panelLogo = new javax.swing.JPanel();
        p_logo = new javax.swing.JPanel();
        l_logo = new javax.swing.JLabel();
        optionScreen = new javax.swing.JPanel();
        p_nav = new javax.swing.JPanel();
        p_logo1 = new javax.swing.JPanel();
        l_logo1 = new javax.swing.JLabel();
        p_menu = new javax.swing.JPanel();
        btn_card = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        btn_buyTqt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 51));
        setResizable(false);

        panelPai.setBackground(new java.awt.Color(255, 204, 51));
        panelPai.setPreferredSize(new java.awt.Dimension(1280, 800));
        panelPai.setLayout(new java.awt.CardLayout());

        loginScreen.setBackground(new java.awt.Color(255, 204, 0));
        loginScreen.setPreferredSize(new java.awt.Dimension(1280, 800));

        panelLogin.setBackground(new java.awt.Color(255, 204, 0));
        panelLogin.setPreferredSize(new java.awt.Dimension(1280, 800));
        panelLogin.setLayout(new java.awt.BorderLayout());

        p_firstLog.setBackground(new java.awt.Color(255, 204, 0));
        p_firstLog.setPreferredSize(new java.awt.Dimension(600, 0));

        p_home.setBackground(new java.awt.Color(247, 245, 245));
        p_home.setPreferredSize(new java.awt.Dimension(400, 90));

        l_Home.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        l_Home.setText("Faça seu Login!");

        javax.swing.GroupLayout p_homeLayout = new javax.swing.GroupLayout(p_home);
        p_home.setLayout(p_homeLayout);
        p_homeLayout.setHorizontalGroup(
            p_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_homeLayout.createSequentialGroup()
                .addContainerGap(167, Short.MAX_VALUE)
                .addComponent(l_Home)
                .addGap(163, 163, 163))
        );
        p_homeLayout.setVerticalGroup(
            p_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_homeLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(l_Home)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        p_ra.setBackground(new java.awt.Color(247, 245, 245));
        p_ra.setPreferredSize(new java.awt.Dimension(400, 100));
        p_ra.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        p_auxRA.setBackground(new java.awt.Color(247, 245, 245));
        p_auxRA.setPreferredSize(new java.awt.Dimension(360, 55));
        p_auxRA.setLayout(new java.awt.BorderLayout(4, 4));

        f_ra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_raActionPerformed(evt);
            }
        });
        p_auxRA.add(f_ra, java.awt.BorderLayout.CENTER);

        l_ra.setBackground(new java.awt.Color(247, 245, 245));
        l_ra.setLabelFor(f_ra);
        l_ra.setText("Registro de Aluno");
        p_auxRA.add(l_ra, java.awt.BorderLayout.PAGE_START);

        p_ra.add(p_auxRA);

        p_password.setBackground(new java.awt.Color(247, 245, 245));
        p_password.setPreferredSize(new java.awt.Dimension(400, 80));
        p_password.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        p_auxPassword.setBackground(new java.awt.Color(247, 245, 245));
        p_auxPassword.setPreferredSize(new java.awt.Dimension(360, 55));
        p_auxPassword.setLayout(new java.awt.BorderLayout(4, 4));

        f_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_passwordActionPerformed(evt);
            }
        });
        p_auxPassword.add(f_password, java.awt.BorderLayout.CENTER);

        l_password.setBackground(new java.awt.Color(255, 255, 255));
        l_password.setText("Senha");
        p_auxPassword.add(l_password, java.awt.BorderLayout.PAGE_START);

        p_password.add(p_auxPassword);

        p_bntlogin.setBackground(new java.awt.Color(247, 245, 245));
        p_bntlogin.setOpaque(false);
        p_bntlogin.setPreferredSize(new java.awt.Dimension(400, 80));

        btn_login.setBackground(new java.awt.Color(247, 245, 245));
        btn_login.setText("Entrar");
        btn_login.setBorder(null);
        btn_login.setBorderPainted(false);
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_bntloginLayout = new javax.swing.GroupLayout(p_bntlogin);
        p_bntlogin.setLayout(p_bntloginLayout);
        p_bntloginLayout.setHorizontalGroup(
            p_bntloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_login, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        p_bntloginLayout.setVerticalGroup(
            p_bntloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_login, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        p_aviso.setBackground(new java.awt.Color(247, 245, 245));
        p_aviso.setPreferredSize(new java.awt.Dimension(400, 90));

        l_aviso.setFont(new java.awt.Font("Segoe UI", 2, 8)); // NOI18N
        l_aviso.setText("* A senha é a mesma do Portal do Aluno");

        javax.swing.GroupLayout p_avisoLayout = new javax.swing.GroupLayout(p_aviso);
        p_aviso.setLayout(p_avisoLayout);
        p_avisoLayout.setHorizontalGroup(
            p_avisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_avisoLayout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(l_aviso)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p_avisoLayout.setVerticalGroup(
            p_avisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_avisoLayout.createSequentialGroup()
                .addComponent(l_aviso, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout p_firstLogLayout = new javax.swing.GroupLayout(p_firstLog);
        p_firstLog.setLayout(p_firstLogLayout);
        p_firstLogLayout.setHorizontalGroup(
            p_firstLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_firstLogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_firstLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p_home, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                    .addComponent(p_ra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p_password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p_bntlogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                    .addComponent(p_aviso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE))
                .addContainerGap())
        );
        p_firstLogLayout.setVerticalGroup(
            p_firstLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_firstLogLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(p_home, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108)
                .addComponent(p_ra, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(p_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(p_bntlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
                .addComponent(p_aviso, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelLogin.add(p_firstLog, java.awt.BorderLayout.WEST);

        panelLogo.setBackground(new java.awt.Color(247, 245, 245));
        panelLogo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0), 4));
        panelLogo.setLayout(new java.awt.BorderLayout());

        p_logo.setBackground(new java.awt.Color(247, 245, 245));

        l_logo.setBackground(new java.awt.Color(247, 245, 245));
        l_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logoutfpr.png"))); // NOI18N
        l_logo.setOpaque(true);

        javax.swing.GroupLayout p_logoLayout = new javax.swing.GroupLayout(p_logo);
        p_logo.setLayout(p_logoLayout);
        p_logoLayout.setHorizontalGroup(
            p_logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_logoLayout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(l_logo, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                .addGap(117, 117, 117))
        );
        p_logoLayout.setVerticalGroup(
            p_logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_logoLayout.createSequentialGroup()
                .addContainerGap(268, Short.MAX_VALUE)
                .addComponent(l_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(261, 261, 261))
        );

        panelLogo.add(p_logo, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout loginScreenLayout = new javax.swing.GroupLayout(loginScreen);
        loginScreen.setLayout(loginScreenLayout);
        loginScreenLayout.setHorizontalGroup(
            loginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginScreenLayout.createSequentialGroup()
                .addGap(0, 955, Short.MAX_VALUE)
                .addComponent(panelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(loginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginScreenLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(969, Short.MAX_VALUE)))
        );
        loginScreenLayout.setVerticalGroup(
            loginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(loginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(loginScreenLayout.createSequentialGroup()
                    .addGap(1, 1, 1)
                    .addComponent(panelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 797, Short.MAX_VALUE)
                    .addGap(2, 2, 2)))
        );

        panelPai.add(loginScreen, "loginScreen");

        optionScreen.setBackground(new java.awt.Color(255, 204, 0));

        p_nav.setBackground(new java.awt.Color(247, 245, 245));
        p_nav.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0), 4));
        p_nav.setLayout(new java.awt.CardLayout());

        p_logo1.setBackground(new java.awt.Color(247, 245, 245));

        l_logo1.setBackground(new java.awt.Color(247, 245, 245));
        l_logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logoutfpr.png"))); // NOI18N
        l_logo1.setOpaque(true);

        javax.swing.GroupLayout p_logo1Layout = new javax.swing.GroupLayout(p_logo1);
        p_logo1.setLayout(p_logo1Layout);
        p_logo1Layout.setHorizontalGroup(
            p_logo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_logo1Layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(l_logo1, javax.swing.GroupLayout.DEFAULT_SIZE, 744, Short.MAX_VALUE)
                .addGap(117, 117, 117))
        );
        p_logo1Layout.setVerticalGroup(
            p_logo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_logo1Layout.createSequentialGroup()
                .addContainerGap(268, Short.MAX_VALUE)
                .addComponent(l_logo1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(261, 261, 261))
        );

        p_nav.add(p_logo1, "lLogo");

        p_menu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0), 4));
        p_menu.setOpaque(false);

        btn_card.setBackground(new java.awt.Color(247, 245, 245));
        btn_card.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        btn_card.setText("CÁRDAPIO DA SEMANA");
        btn_card.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cardActionPerformed(evt);
            }
        });

        btn_exit.setBackground(new java.awt.Color(247, 245, 245));
        btn_exit.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        btn_exit.setText("SAIR");
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });

        btn_buyTqt.setBackground(new java.awt.Color(247, 245, 245));
        btn_buyTqt.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        btn_buyTqt.setText("COMPRAR TICKET");
        btn_buyTqt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buyTqtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_menuLayout = new javax.swing.GroupLayout(p_menu);
        p_menu.setLayout(p_menuLayout);
        p_menuLayout.setHorizontalGroup(
            p_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_menuLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(p_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_card, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buyTqt, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        p_menuLayout.setVerticalGroup(
            p_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_menuLayout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(btn_card, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(btn_buyTqt, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout optionScreenLayout = new javax.swing.GroupLayout(optionScreen);
        optionScreen.setLayout(optionScreenLayout);
        optionScreenLayout.setHorizontalGroup(
            optionScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, optionScreenLayout.createSequentialGroup()
                .addComponent(p_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p_nav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        optionScreenLayout.setVerticalGroup(
            optionScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p_nav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(p_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelPai.add(optionScreen, "optionScreen");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        if(bancoDeDados.verificaDados(f_ra.getText(), f_password.getText())){
            CardLayout cl = (CardLayout) panelPai.getLayout();
            cl.show(panelPai, "optionScreen");
            f_ra.setText("");
            f_password.setText("");
        }else
            JOptionPane.showMessageDialog(rootPane,"Dados Invalidos");
    }//GEN-LAST:event_btn_loginActionPerformed

    private void f_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_passwordActionPerformed

    }//GEN-LAST:event_f_passwordActionPerformed

    private void f_raActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_raActionPerformed

    }//GEN-LAST:event_f_raActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        CardLayout cl = (CardLayout) panelPai.getLayout();
        cl.show(panelPai, "loginScreen");
    }//GEN-LAST:event_btn_exitActionPerformed

    private void btn_cardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cardActionPerformed

       
    }//GEN-LAST:event_btn_cardActionPerformed

    private void btn_buyTqtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buyTqtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_buyTqtActionPerformed

    /**
     * @param args the command line arguments
     */   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjetoAnaliseDeSistemas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjetoAnaliseDeSistemas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjetoAnaliseDeSistemas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjetoAnaliseDeSistemas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjetoAnaliseDeSistemas().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buyTqt;
    private javax.swing.JButton btn_card;
    private javax.swing.JButton btn_exit;
    private javax.swing.JToggleButton btn_login;
    private javax.swing.JPasswordField f_password;
    private javax.swing.JTextField f_ra;
    private javax.swing.JLabel l_Home;
    private javax.swing.JLabel l_aviso;
    private javax.swing.JLabel l_logo;
    private javax.swing.JLabel l_logo1;
    private javax.swing.JLabel l_password;
    private javax.swing.JLabel l_ra;
    private javax.swing.JPanel loginScreen;
    private javax.swing.JPanel optionScreen;
    private javax.swing.JPanel p_auxPassword;
    private javax.swing.JPanel p_auxRA;
    private javax.swing.JPanel p_aviso;
    private javax.swing.JPanel p_bntlogin;
    private javax.swing.JPanel p_firstLog;
    private javax.swing.JPanel p_home;
    private javax.swing.JPanel p_logo;
    private javax.swing.JPanel p_logo1;
    private javax.swing.JPanel p_menu;
    private javax.swing.JPanel p_nav;
    private javax.swing.JPanel p_password;
    private javax.swing.JPanel p_ra;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPanel panelLogo;
    private javax.swing.JPanel panelPai;
    // End of variables declaration//GEN-END:variables
}
