@startuml SELF-RU

title SELF-RU

object window <<JFrame>>

together {
    object mainScreen <<MainClass>>{
        bancoDeDados
        alunosCompraram
    }
    object loginScreen <<LoginScreen>> {
        name = loginScreen
        estudanteLogado
        ticketEstudanteLogado
    }
    object optionScreen <<OptionScreen>> {
        name = optionScreen
        estudanteLogado
        ticketEstudanteLogado
    }
    object purchaseScreen <<PurchaseScreen>>{
        name = purchaseScreen
        total
        ticket
        estudanteLogado
        ticketEstudanteLogado
    }
    object cardScreen <<CardScreen>> {
        name = cardScreen
        valorCompra
        tipoCartao
        estudanteLogado
        ticketEstudanteLogado
    }
    object menuScreen <<MenuScreen>> {
        name = menuScreen
        estudanteLogado
        ticketEstudanteLogado
    }
}

object ticket <<Ticket>>{
    basePrice= 3.50
    adicionais
    valorTotal
}

object aluno <<Aluno>> {
        RA = 2192942
        name = Guilherme Marcos
        eMail = gmarcos@alunos.utfpr.edu.br
        password = *********
        ticket
}

together {
    object conexao <<ConexaoMySQL>>{
        status = naoconectou...
        databaseName
    }

    object bancoDeDados <<BancoDeDados>>{
        conexao
        estudante
    }
}

object eMail <<Email>>{
    emailOrigem = self.ru.05@gmail.com
    senhaEmailOrigem = *************
    hostName = smtp.gmail.com
    hostPort = 465
}



window -> mainScreen
mainScreen -> bancoDeDados
mainScreen --> loginScreen
loginScreen <--> optionScreen
optionScreen <-right> menuScreen
loginScreen -left- bancoDeDados
optionScreen <--> purchaseScreen
purchaseScreen <-> cardScreen
purchaseScreen -> ticket
purchaseScreen -- bancoDeDados
cardScreen -- aluno
cardScreen --> loginScreen
cardScreen -- eMail
cardScreen -- bancoDeDados
bancoDeDados --> aluno
bancoDeDados --> conexao
ticket -- aluno


@enduml