@startuml SELF-RU

title SELF-RU

together {
    object loginScreen <<LoginScreen>> {
        name = loginScreen
    }

    object optionScreen <<OptionScreen>> {
        name = optionScreen
    }
    object purchaseScreen <<PurchaseScreen>>{
        total = 00.00
    }
    object cardScreen <<CardScreen>> {
        name = cardScreen
    }
    object menuScreen <<MenuScreen>> {
        name = menuScreen
    }
}

object ticket <<Aluno>>{
    basePrice= 30.00
}

object aluno <<Aluno>> {
        RA = 2192942
        name = Guilherme Marcos
        eMail = gmarcos@alunos.utfpr.edu.br
        password = guilherme0209
}

object bdLogin <<BancoDeDados>>

object mainScreen <<MainClass>>

object bdCompra <<BancoDeDados>>

object jFrame <<JFrame>>



jFrame -right- mainScreen
mainScreen --> loginScreen
loginScreen -right- bdLogin
bdLogin -- aluno
ticket -- aluno
loginScreen <--> optionScreen
optionScreen <-left-> menuScreen
optionScreen <--> purchaseScreen
purchaseScreen -down- ticket
purchaseScreen <-right-> cardScreen
cardScreen --> loginScreen
cardScreen -- bdCompra
cardScreen -right- aluno
@enduml